// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl9GWeXlC9fxPvY0wnvuzAZD4Jmrrh9kQ',
    appId: '1:633537696725:web:3fb637ab947a9e00ef635c',
    messagingSenderId: '633537696725',
    projectId: 'learnio-edu-platform',
    authDomain: 'learnio-edu-platform.firebaseapp.com',
    storageBucket: 'learnio-edu-platform.firebasestorage.app',
    measurementId: 'G-6FNLRMLLPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhLcWAUVXoTWv8GUGTpp92eTvWwR8Rvyc',
    appId: '1:633537696725:android:a995d903657de054ef635c',
    messagingSenderId: '633537696725',
    projectId: 'learnio-edu-platform',
    storageBucket: 'learnio-edu-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJGTpesXGZxvq7khVtOxoCX0MIAyfa5QI',
    appId: '1:633537696725:ios:3f24e5870aface4bef635c',
    messagingSenderId: '633537696725',
    projectId: 'learnio-edu-platform',
    storageBucket: 'learnio-edu-platform.firebasestorage.app',
    iosClientId: '633537696725-f8os6p9tvvrgj0v1tagrlbppcjc5o5un.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJGTpesXGZxvq7khVtOxoCX0MIAyfa5QI',
    appId: '1:633537696725:ios:3f24e5870aface4bef635c',
    messagingSenderId: '633537696725',
    projectId: 'learnio-edu-platform',
    storageBucket: 'learnio-edu-platform.firebasestorage.app',
    iosClientId: '633537696725-f8os6p9tvvrgj0v1tagrlbppcjc5o5un.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl9GWeXlC9fxPvY0wnvuzAZD4Jmrrh9kQ',
    appId: '1:633537696725:web:89ee5db94a457b6aef635c',
    messagingSenderId: '633537696725',
    projectId: 'learnio-edu-platform',
    authDomain: 'learnio-edu-platform.firebaseapp.com',
    storageBucket: 'learnio-edu-platform.firebasestorage.app',
    measurementId: 'G-RGZ8FL1Q11',
  );
}
